### ISSUE TITLE
Lasers and Light Bridges can't pass through portals

### ISSUE THREAD

**Issue by vrad-exe** [Adrodoc55/ApertureCraftVanilla#19]
![2017-02-16_10 31 54](https://cloud.githubusercontent.com/assets/19228201/23035244/4e1c41ee-f433-11e6-9e53-d9322dc9add2.png)

I've tried restarting the laser system while the portal system is still active, but that doesn't fix it. Am I just doing something wrong?

**Comment by Adrodoc** [comment]
@Luke18033 I assume you use Minecraft 1.11.2 and ACV 9.0.0 (please correct me if I am wrong). Can you please tell me if you enabled smooth teleportation?

**Comment by vrad-exe** [comment]
9.0.0 on 1.11.2. Smooth Teleportation is on, turning it off fixes the problem.

**Comment by Adrodoc** [comment]
@Luke18033 I can't reproduce the bridge problem, they always work for me. Lasers work for me if smooth teleportation is off, but not if it is on. This is weird, because it is the opposite of what you experience. Are you sure that turning it off fixes it for you and not the other way around?

**Comment by Adrodoc** [comment]
@Luke18033 My issue is fixed by restarting the main portal system, so maybe #9 has been reversed at some point so that the laser system now has to be started first. I still can't reproduce the problem you have with bridges.
Please redownload v9.0.0, open the demo world in 1.11.2 and follow these steps in the exact same order:
1. Install the system
2. Turn on the lasers
3. Turn on smooth teleportation
4. Turn on portals
5. Shoot portals at the walls opposite of the laser and bridge spawner
6. Turn on laser and bridge spawner

After these steps everything worked fine for me (the bridges and lasers are properly teleported). Does that work for you too?

**Comment by Adrodoc** [comment]
@Luke18033 Does your problem still persist or can I close this issue?

**Comment by vrad-exe** [comment]
I haven't tried reinstalling yet. I haven't been playing Minecraft much recently, I've been working on actual Portal 2 maps.

**Comment by vrad-exe** [comment]
Alright, so...after several months of completely forgetting about this, I finally installed the latest version and tested if this bug still occurred. Looks like it's been fixed.
![2017-11-10_08 57 22](https://user-images.githubusercontent.com/19228201/32669501-9fdc5bf6-c5f5-11e7-81e3-fca2aefa4480.png)

**Comment by Adrodoc** [comment]
@Luke18033 Very nice!
