### ISSUE TITLE
1.13?

### ISSUE THREAD

**Issue by vrad-exe** [Adrodoc55/ApertureCraftVanilla#20]
Is this ever going to be updated for 1.13? The update has been out for months now and there haven't been any new commits since 2017. Seems pretty dead at this point.

**Comment by Adrodoc** [comment]
Unfortunately you are right. It seems unlikely that ACV will be updated to 1.13. I have a full time job now, that is why I don't work at this project at the moment.
It is not the first time that I stopped working on ACV for several months, but it might be the last time.
Even if ACV is dead the project has inspired other people to build on top of it. In particular [Ersatz](https://www.youtube.com/channel/UClfq20CeYnZ2_Rm72VgUPXg) and [Lidcer](https://www.youtube.com/channel/UCBUIy2fvbjCpl17e7HiEIAQ) have advanced Portal Implementations, both of which are updated to 1.13 I believe.
Since ACV is an open source project anyone (including you) can adopt it and build on top of the [branch for 1.13](https://github.com/Adrodoc/ApertureCraftVanilla/tree/1.13). The main portal mechanics (shooting portals and teleportation) are implemented if I remember correctly.
There is still a chance I come back to this project at some point, but the future is uncertain, so I can't make any promises.

**Comment by vrad-exe** [comment]
Oh, I didn't see that branch! Still hasn't been updated in a few months though. I'll check out some of those other portal implementations. (Ersatz's seems to be based on ACV though, so about that...) I also might look into trying to port some parts of ACV myself if it's not too difficult.

**Comment by Adrodoc** [comment]
@Luke18033 I just realized that ApertureCraft Vanilla will get 5 years old next month.
